
---
- hosts: dev
  become: yes
  remote_user: ec2-user
  tasks:
    - name: Install Apache.
      yum: name={{ item }} state=present
      with_items:
      - httpd
      - php
      - php-mysql
    - name: Install OpenJDK
      yum: name=java-1.6.0-openjdk-devel state=present
    - name: Make my directory tree readable
      file:
        path: /var/www/html/
        mode: u=rwX,g=rX,o=rX
        recurse: yes
        owner: apache
        group: apache
    - name: Make sure Apache is started now and at boot.
      service: name=httpd state=started enabled=yes
    - name: Install Unzip
      yum: name=unzip state=present
    - name: Install GTAR     
      yum: name=tar state=present   
    - name: Create gradle directory
      file:
        path: /opt/gradle
        state: directory
    - name: Download Gradle
      get_url:
         url: https://services.gradle.org/distributions/gradle-5.3.1-bin.zip
         dest: /tmp
    - name: Extract Gradle
      shell: unzip /tmp/gradle-5.3.1-bin.zip -d /opt/gradle/
    - name: Set Env
      shell: export PATH=$PATH:/opt/gradle/gradle-5.3.1/bin
        


